### ISSUE TITLE
error: database is uninitialized and password option is not specified 

### ISSUE THREAD

**Issue by tetsu5555** [tetsu5555/go-docker#1]
`docker-compose up`すると以下のようなエラーが出る

```
db_1       | error: database is uninitialized and password option is not specified 
db_1       |   You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```

**Comment by tetsu5555** [comment]
以下の記事を参考に修正
https://stackoverflow.com/questions/39678463/docker-compose-database-is-uninitialized

**Comment by tetsu5555** [comment]
以下のように修正

```
    environment:
      MYSQL_DATABASE: school
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: ""
```
↓
```
    environment:
      MYSQL_DATABASE: school
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_ALLOW_EMPTY_PASSWORD: ""
```
